force failure for debug
EXCEPTION: Exception calling "Add" with "2" argument(s): "Item has
already been added. Key in dictionary: 'OneVM'  Key being added:
'OneVM'"

[ERROR] Source: Line 199 in script TestControllers\TestController.psm1.